import "~/styles/globals.css";

import { Urbanist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "~/components/layout/Navbar";
import SideBar from "~/components/layout/SideBar";
import { Toaster } from "~/components/ui/sonner";

const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${urbanist.variable} `}>
        <TRPCReactProvider>
          <main className="mx-auto max-w-5xl space-y-6 px-3 py-10">
            <Navbar />
            <main className="flex gap-6">
              <SideBar />
              <div className="basis-full">{children}</div>
            </main>
            <Toaster />
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
